# This file was generated by GoReleaser. DO NOT EDIT.
cask "krakenkey" do
  version "0.8.0"

  on_macos do
    on_arm do
      sha256 "2908a6ce9a3557c670df0262c009f0b86a559de031d698fe9ed8f1d8869c8691"
      url "https://github.com/KrakenKey/cli/releases/download/v#{version}/krakenkey_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "455ba7f7662430513af55a94c6bc55a15461e3afbd50c2709485db00d718569d"
      url "https://github.com/KrakenKey/cli/releases/download/v#{version}/krakenkey_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "29626ccb4f7ed3d55be03ca6b39022a9ecf57d4ca7e69427a9a750301f3ebcf1"
      url "https://github.com/KrakenKey/cli/releases/download/v#{version}/krakenkey_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2698582704631784934fa5416d7336189e51ad0e8a41382706dc00c7451bb236"
      url "https://github.com/KrakenKey/cli/releases/download/v#{version}/krakenkey_#{version}_linux_amd64.tar.gz"
    end
  end

  name "krakenkey"
  desc "TLS certificates and endpoint monitoring from the terminal"
  homepage "https://krakenkey.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "krakenkey"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/krakenkey"]
    end
  end

  # No zap stanza required
end
