# This file was generated by GoReleaser. DO NOT EDIT.
cask "krakenkey" do
  version "0.8.1"

  on_macos do
    on_arm do
      sha256 "711474f059d4c4a56badbd1e46451984a9a701d87b73380b6fa3ff24a3fde5ce"
      url "https://github.com/KrakenKey/cli/releases/download/v#{version}/krakenkey_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0b0144d1175f0c700e5294c037fe398bd421467efe53dced1521423463e8d4c8"
      url "https://github.com/KrakenKey/cli/releases/download/v#{version}/krakenkey_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "40e561911b8af8d50087de4d5fc8b1f47789d4bb39b7affc8dfcad34aa5c36e1"
      url "https://github.com/KrakenKey/cli/releases/download/v#{version}/krakenkey_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "30c7d728fd8b3182144982ed5da559ec5f5b61cc33a8ccc2c660aa45c3a5dd01"
      url "https://github.com/KrakenKey/cli/releases/download/v#{version}/krakenkey_#{version}_linux_amd64.tar.gz"
    end
  end

  name "krakenkey"
  desc "TLS certificates and endpoint monitoring from the terminal"
  homepage "https://krakenkey.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "krakenkey"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/krakenkey"]
    end
  end

  # No zap stanza required
end
